### ISSUE TITLE
Error: Line 3: Unexpected reserved word

### ISSUE THREAD

**Issue by trusktr** [hughsk/colony#17]
Getting this error while following instructions in the README:

```
❯ git clone https://github.com/trusktr/infamous
❯ cd infamous
❯ npm install
❯ npm run build-cjs
❯ colony ./index.js -o colony
/usr/local/lib/node_modules/colony/bin/colony:101
    if (err) throw err
             ^

Error: Line 3: Unexpected reserved word
    at throwError (/usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:1151:21)
    at throwUnexpected (/usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:1202:17)
    at parsePrimaryExpression (/usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:1577:16)
    at /usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:3295:38
    at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:1669:48)
    at parsePostfixExpression (/usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:1710:20)
    at /usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:3295:38
    at parseUnaryExpression (/usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:1770:16)
    at /usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:3295:38
    at parseMultiplicativeExpression (/usr/local/lib/node_modules/colony/node_modules/esprima/esprima.js:1776:20)
```

**Comment by Claire** [comment]
+1

**Comment by rubikonx9** [comment]
Same happens for me.
