### ISSUE TITLE
Got trouble in WinXP

### ISSUE THREAD

**Issue by coderaiser** [hughsk/colony#2]
Hello,
your program looks very interesting, but i could not start it correctly

Trouble on WinXP sp3 (russian).
I was install colony thru npm.

```
npm install -g serve colony
```

Then start it.

```
D:\Temp>colony --npm browserify
CreateProcessW: ?? ??????? ????? ????????? ????.

C:\Documents and Settings\ilja\Application Data\npm\nod
ny:81
    if (err) throw err
                   ^
Error: NPM exited with code 127
    at ChildProcess.colony.npm (C:\Documents and Settin
npm\node_modules\colony\lib\index.js:104:41)
    at ChildProcess.g (events.js:185:14)
    at ChildProcess.EventEmitter.emit (events.js:91:17)
    at Process._handle.onexit (child_process.js:674:10)
```

Versions:

```
node --version
v0.8.2
npm -v
1.1.36
```

**Comment by hughsk** [comment]
Hey, thanks for pointing this out - looks like an issue with spawning the NPM child process, which works differently with Windows (and I haven't tested it yet).

I'll have a look and see what I can do :)

**Comment by coderaiser** [comment]
Okey, thank you :)

**Comment by hughsk** [comment]
New version published to NPM, which works for me on Windows 7. Try `npm install -g colony` again and it should work this time :)

**Comment by coderaiser** [comment]
Thank you, it worked for me. Looks very beautiful :). So I want look at [my project](//github.com/coderaiser/cloudcmd). I wrote

```
colony --npm cloudcmd
```

I saw this

```
C:\Documents and Settings\coderaiser\colony.tmp\node_modules\cloudcmd\node_modules\so
cket.io\node_modules\socket.io-client\node_modules\ws>node "C:\Program Files\nod
ejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild
npm http 304 https://registry.npmjs.org/html-minifier/0.4.5
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/wordwrap
cloudcmd@0.1.8 node_modules\cloudcmd
├── socket.io@0.9.10 (policyfile@0.0.4, redis@0.7.2, socket.io-client@0.9.10)
└── minify@0.1.8 (html-minifier@0.4.5, uglify-js@1.3.4, css-b64-images@0.2.1, cl
ean-css@0.8.2)

C:\Documents and Settings\coderaiser\Application Data\npm\node_modules\colony\lib\ind
ex.js:25
            return highlight(lang, value)
                                   ^
ReferenceError: value is not defined
    at Object.marked.setOptions.highlight (C:\Documents and Settings\coderaiser\Appli
cation Data\npm\node_modules\colony\lib\index.js:25:36)
    at tok (C:\Documents and Settings\coderaiser\Application Data\npm\node_modules\co
lony\node_modules\marked\lib\marked.js:531:30)
    at parse (C:\Documents and Settings\coderaiser\Application Data\npm\node_modules\
colony\node_modules\marked\lib\marked.js:638:12)
    at marked (C:\Documents and Settings\coderaiser\Application Data\npm\node_modules
\colony\node_modules\marked\lib\marked.js:707:10)
    at colony.generate (C:\Documents and Settings\coderaiser\Application Data\npm\nod
e_modules\colony\lib\index.js:65:40)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

Same error for

```
colony --npm minify
```

and

```
colony --npm uglify-js
```

But

```
colony --npm browserify
```

Works great.

**Comment by hughsk** [comment]
Ah, a small mistake on my part there - thanks again for pointing it out, just published another fix :)

Gave it a shot with cloudcmd, but because of the way you're using `require`, [detective](/substack/node-detective) won't pick it up - for example [here](https://github.com/coderaiser/cloudcmd/blob/master/cloudcmd.js#L5) you'd need to use `'./lib/server/main'` instead of `DIR + 'lib/server/main'`. Hope it helps!
